# clair/Rakefile
require 'mkmf'

# =============================================================================
# PART 1: CONSTANTS & CONFIGURATION
# =============================================================================

SRC_DIR   = "src"
TOOLS_DIR = "tools"
CONFIG    = '.config.rb'

# --- Tool Discovery & Caching ---
if File.exist?(CONFIG)
  require_relative CONFIG
else
  puts "===> Performing tool check..."

  GCC = find_executable('gcc')
  CC  = find_executable('cc')

  abort "ERROR: 'gcc' or 'cc' not found. Please install build tools." unless GCC and CC

  File.open(CONFIG, 'w') do |file|
    file.puts "# Auto-generated by Rakefile. Do not edit."
    file.puts "CC  = '#{CC}'"
    file.puts "GCC = '#{GCC}'"
  end
  puts "===> Tool paths cached in '#{CONFIG}'"
end

CFLAGS = "-Wall -Werror"

C_GEN_MAP = {
  "#{SRC_DIR}/clair-errno.ads"    => "#{TOOLS_DIR}/gen-clair-errno-ads",
  "#{SRC_DIR}/clair-platform.ads" => "#{TOOLS_DIR}/gen-clair-platform-ads",
  "#{SRC_DIR}/clair-errno-raise_from_errno.adb" => "#{TOOLS_DIR}/gen-clair-errno-raise_from_errno-adb"
}

BUILT_ADA   = C_GEN_MAP.keys
BUILT_TOOLS = C_GEN_MAP.values

# =============================================================================
# PART 2: FILE GENERATION RULES
# =============================================================================

BUILT_TOOLS.each do |tool|
  file tool => "#{tool}.c" do |t|
    sh "#{CC} #{CFLAGS} #{t.source} -o #{t.name}"
  end
end

C_GEN_MAP.each do |target, tool|
  file target => tool do
    sh "#{tool} > #{target}"
  end
end

# =============================================================================
# PART 3: TASKS
# =============================================================================

desc "Generate all Ada files (default)"
task :default => :build

desc "Generate all Ada files"
task :gen => BUILT_ADA

desc "Generate specs and build library"
task :build, [:os_name] => :gen do |t, args|
  os_name = args[:os_name]

  if os_name.nil?
    opt = ""
  else
    opt = "-XOS=#{os_name}"
  end

  sh "gprbuild #{opt} -P clair.gpr"
  sh "gprbuild #{opt} -P tests/tests_clair.gpr"
end

task :clean do
  puts "===> Cleaning gprbuild artifacts..."

  begin
    sh "gprclean -r -P clair.gpr"
    sh "gprclean -r -P tests/tests_clair.gpr"
  rescue RuntimeError
    puts "Warning: gprclean failed (likely due to missing source files)."
    puts "         Proceeding with forced cleanup."
  end

  puts "Cleaning generated files..."
  rm_f FileList[ CONFIG, "mkmf.log" ]
  rm_f BUILT_ADA
  rm_f BUILT_TOOLS
  rm_rf ["bin", "lib", "obj"]
end
