# clair/Rakefile
require 'mkmf'

# =============================================================================
# PART 1: CONSTANTS & CONFIGURATION
# =============================================================================

SRC_DIR   = "src"
TOOLS_DIR = "tools"
CONFIG    = '.config.rb'

# --- Tool Discovery & Caching ---
if File.exist?(CONFIG)
  require_relative CONFIG
else
  puts "===> Performing tool check..."

  GCC = find_executable('gcc')
  CC  = find_executable('cc')

  abort "ERROR: 'gcc' or 'cc' not found. Please install build tools." unless GCC and CC

  File.open(CONFIG, 'w') do |file|
    file.puts "# Auto-generated by Rakefile. Do not edit."
    file.puts "CC  = '#{CC}'"
    file.puts "GCC = '#{GCC}'"
  end
  puts "===> Tool paths cached in '#{CONFIG}'"
end

CFLAGS = "-Wall -Werror"

# --- Generated File Definitions ---
SPECS_MAP = {
  "#{SRC_DIR}/signal_h.ads" => "/usr/include/signal.h",
}

BUILT_ADS = FileList[
  "#{SRC_DIR}/clair-dl.ads",
  "#{SRC_DIR}/clair-error.ads",
  "#{SRC_DIR}/clair-file.ads",
  "#{SRC_DIR}/clair-types.ads"
]

BUILT_PROGS = FileList[
  "#{TOOLS_DIR}/gen-clair-dl-ads",
  "#{TOOLS_DIR}/gen-clair-file-ads",
  "#{TOOLS_DIR}/gen-clair-types-ads"
]

# =============================================================================
# PART 2: FILE GENERATION RULES
# =============================================================================

file "#{SRC_DIR}/clair-error.ads" => "#{TOOLS_DIR}/gen-clair-error-ads.rb" do |ads|
  sh "ruby #{TOOLS_DIR}/gen-clair-error-ads.rb > #{ads}"
end

file "#{SRC_DIR}/clair-dl.ads" => "#{TOOLS_DIR}/gen-clair-dl-ads" do |ads|
  sh "#{TOOLS_DIR}/gen-clair-dl-ads > #{ads}"
end

file "#{TOOLS_DIR}/gen-clair-dl-ads" => "#{TOOLS_DIR}/gen-clair-dl-ads.c" do |t|
  sh "#{CC} #{CFLAGS} #{t.source} -o #{t.name}"
end

file "#{SRC_DIR}/clair-file.ads" => "#{TOOLS_DIR}/gen-clair-file-ads" do |ads|
  sh "#{TOOLS_DIR}/gen-clair-file-ads > #{ads}"
end

file "#{TOOLS_DIR}/gen-clair-file-ads" => "#{TOOLS_DIR}/gen-clair-file-ads.c" do |t|
  sh "#{CC} #{CFLAGS} #{t.source} -o #{t.name}"
end

file "#{SRC_DIR}/clair-types.ads" => "#{TOOLS_DIR}/gen-clair-types-ads" do |ads|
  sh "#{TOOLS_DIR}/gen-clair-types-ads > #{ads}"
end

file "#{TOOLS_DIR}/gen-clair-types-ads" => "#{TOOLS_DIR}/gen-clair-types-ads.c" do |t|
  sh "#{CC} #{CFLAGS} #{t.source} -o #{t.name}"
end

# Rule to generate Ada specs from C headers
SPECS_MAP.each do |ads, header|
  file ads => header do |t|
    sh "cd #{SRC_DIR} && #{GCC} -c -fdump-ada-spec " \
       "-D_POSIX_C_SOURCE=200809L #{t.prerequisites.first}"
  end
end

# =============================================================================
# PART 3: TASKS
# =============================================================================

desc "Generate all Ada spec files (default)"
task :default => :gen_specs

desc "Generate all Ada spec files"
task :gen_specs => BUILT_ADS + SPECS_MAP.keys

desc "Generate specs and build library"
task :build => :gen_specs do
  sh "gprbuild -P clair.gpr"
  sh "gprbuild -P tests/tests_clair.gpr"
end

task :clean do
  puts "===> Cleaning gprbuild artifacts..."
  sh "gprclean -r -P clair.gpr"
  sh "gprclean -r -P tests/tests_clair.gpr"
  puts "Cleaning generated files..."
  rm_f FileList[ CONFIG, "mkmf.log", "#{SRC_DIR}/*_h.ads" ]
  rm_f BUILT_ADS
  rm_f BUILT_PROGS
end
