# clair/Rakefile
require 'mkmf'

# =============================================================================
# PART 1: CONSTANTS & CONFIGURATION
# =============================================================================

# --- Path Constants ---
SRC_DIR   = "src"
BUILD_DIR = "build"
TOOLS_DIR = "tools"
TESTS_DIR = "tests"
CONFIG    = '.config.rb'

# --- Tool Discovery & Caching ---
if File.exist?(CONFIG)
  require_relative CONFIG
else
  puts "===> Performing tool check..."

  # --- Tool Paths ---
  # Find GNAT, AR, and GCC executables automatically
  GNATMAKE = %w[gnatmake gnatmake14 gnatmake13 gnatmake12
                gnatmake-14 gnatmake-13 gnatmake-12].find do |cmd|
    find_executable(cmd)
  end
  abort "ERROR: gnatmake not found. Please install GNAT." unless GNATMAKE

  AR  = find_executable('ar')
  GCC = find_executable('gcc')
  CC  = find_executable('cc')

  abort "ERROR: 'gcc' or 'ar' not found. Please install build tools." unless GCC and GCC and CC

  # Save the found paths as Ruby code in the config file.
  File.open(CONFIG, 'w') do |file|
    file.puts "# Auto-generated by Rakefile. Do not edit."
    file.puts "# Run 'rake clean' to re-detect tools."
    file.puts
    file.puts "AR       = '#{AR}'"
    file.puts "CC       = '#{CC}'"
    file.puts "GCC      = '#{GCC}'"
    file.puts "GNATMAKE = '#{GNATMAKE}'"
  end
  puts "===> Tool paths cached in '#{CONFIG}'"
end

# --- Source & Object File Lists ---
CFLAGS = "-Wall -Werror"
ADA_CFLAGS = "-cargs -fPIC -gnat2022 -largs -nostartfiles -margs -D " + BUILD_DIR
ADB_SOURCES = FileList[ "#{SRC_DIR}/clair-dl.adb",
                        "#{SRC_DIR}/clair-error.adb",
                        "#{SRC_DIR}/clair-file.adb",
                        "#{SRC_DIR}/clair-process.adb",
                        "#{SRC_DIR}/clair-signal.adb" ]
C_SOURCES   = FileList[ "#{SRC_DIR}/clair-error-c.c" ]

ADA_OBJECTS = ADB_SOURCES.pathmap("#{BUILD_DIR}/%n.o")
C_OBJECTS   = C_SOURCES.pathmap("#{BUILD_DIR}/%n.o")
OBJECTS     = ADA_OBJECTS + C_OBJECTS

# The following file list must be updated manually.
LIB_OBJECTS = [
  "build/clair-types.o",
  "build/clair-dl.o",
  "build/clair.o",
  "build/clair-error-c.o",
  "build/clair-error.o",
  "build/clair-file.o",
  "build/clair-process.o",
  "build/clair-signal.o",
  "build/sys_usigset_h.o",
  "build/sys_usigval_h.o",
  "build/sys_signal_h.o",
  "build/sys_utypes_h.o"]

# --- Generated File Definitions ---
SPECS_MAP = {
  "#{SRC_DIR}/signal_h.ads" => "/usr/include/signal.h",
}

# --- Generated File Definitions ---
# Ada files created by the generators
BUILT_ADS = FileList[ "#{SRC_DIR}/clair-dl.ads",
                      "#{SRC_DIR}/clair-error.ads",
                      "#{SRC_DIR}/clair-file.ads",
                      "#{SRC_DIR}/clair-types.ads" ]

BUILT_PROGS = FileList[ "#{TOOLS_DIR}/gen-clair-dl-ads",
                        "#{TOOLS_DIR}/gen-clair-file-ads",
                        "#{TOOLS_DIR}/gen-clair-types-ads" ]

# --- Library File Name Definitions ---
SHARED_LIB = File.join(BUILD_DIR, "libclair.so")
STATIC_LIB = File.join(BUILD_DIR, "libclair.a")

# =============================================================================
# PART 2: BUILD RULES & FILE TASKS (The "How")
# =============================================================================

# Create the build directory as a task, so other tasks can depend on it.
directory BUILD_DIR

file "#{SRC_DIR}/clair-error.ads" =>
     "#{TOOLS_DIR}/gen-clair-error-ads.rb" do |ads|
  sh "ruby #{TOOLS_DIR}/gen-clair-error-ads.rb > #{ads}"
end

file "#{SRC_DIR}/clair-dl.ads" => "#{TOOLS_DIR}/gen-clair-dl-ads" do |ads|
  sh "#{TOOLS_DIR}/gen-clair-dl-ads > #{ads}"
end

file "tools/gen-clair-dl-ads" => "tools/gen-clair-dl-ads.c" do |t|
  sh "#{CC} #{CFLAGS} #{t.source} -o  #{t.name}"
end

file "#{SRC_DIR}/clair-file.ads" => "#{TOOLS_DIR}/gen-clair-file-ads" do |ads|
  sh "#{TOOLS_DIR}/gen-clair-file-ads > #{ads}"
end

file "tools/gen-clair-file-ads" => "tools/gen-clair-file-ads.c" do |t|
  sh "#{CC} #{CFLAGS} #{t.source} -o  #{t.name}"
end

file "#{SRC_DIR}/clair-types.ads" => "#{TOOLS_DIR}/gen-clair-types-ads" do |ads|
  sh "#{TOOLS_DIR}/gen-clair-types-ads > #{ads}"
end

file "tools/gen-clair-types-ads" => "tools/gen-clair-types-ads.c" do |t|
  sh "#{CC} #{CFLAGS} #{t.source} -o  #{t.name}"
end

file "#{SRC_DIR}/clair-dl.adb"      => "#{SRC_DIR}/clair-dl.ads"
file "#{SRC_DIR}/clair-error.adb"   => "#{SRC_DIR}/clair-error.ads"
file "#{SRC_DIR}/clair-file.adb"    => "#{SRC_DIR}/clair-file.ads"
file "#{SRC_DIR}/clair-process.adb" => "#{SRC_DIR}/clair-process.ads"
file "#{SRC_DIR}/clair-signal.adb"  => "#{SRC_DIR}/clair-signal.ads"
file "#{SRC_DIR}/clair-types.adb"   => "#{SRC_DIR}/clair-types.ads"

file "#{BUILD_DIR}/clair-file.o"    => ["#{SRC_DIR}/clair-file.adb",
                                        "#{SRC_DIR}/clair-types.ads"]

ADA_OBJECTS.each do |object|
  source = object.pathmap("#{SRC_DIR}/%n.adb")

  file object => [source, "src/clair-error.ads", BUILD_DIR ] do |t|
    sh "#{GNATMAKE} -c -I#{SRC_DIR} #{t.source} #{ADA_CFLAGS}"
  end
end

# Generic rule for compiling C source files
rule '.o' => ->(t) { t.pathmap("#{SRC_DIR}/%n.c") } do |t|
  sh "#{CC} #{CFLAGS} -fPIC -c #{t.source} -o #{t.name}"
end

# Rule to generate Ada specs from C headers
SPECS_MAP.each do |ads, header|
  file ads => header do |t|
    sh "cd #{SRC_DIR} && #{GCC} -c -fdump-ada-spec " \
       "-D_POSIX_C_SOURCE=200809L #{t.prerequisites.first}"
  end
end

# Rule to build the shared library
file SHARED_LIB => SPECS_MAP.keys + OBJECTS do |t|
  sh "#{CC} #{CFLAGS} -shared #{LIB_OBJECTS.join(' ')} -o #{t.name}"
end

# Rule to build the static library
file STATIC_LIB => SPECS_MAP.keys + OBJECTS do |t|
  sh "#{AR} rcs #{t.name} #{LIB_OBJECTS.join(' ')}"
end

# =============================================================================
# PART 3: MAIN & UTILITY TASKS (The "What")
# =============================================================================

multitask :gen_c_specs => SPECS_MAP.keys
multitask :c_objects   => C_OBJECTS

# --- User-Facing Tasks ---

task :default => [ SHARED_LIB, STATIC_LIB ]

desc "Compile and link the test executables"
task :tests => [STATIC_LIB] do
  puts "===> Building test suite..."

  test_dir = "tests"
  test_main_file = File.join(test_dir, "test_clair_signal_main.adb")
  test_exe = File.join(test_dir, "test-clair-signal")

  sh "#{GNATMAKE} -I#{SRC_DIR} -I#{test_dir} #{test_main_file} " \
     "-o #{test_exe} " \
     "-largs #{STATIC_LIB} " \
     "-margs -D #{BUILD_DIR}"

  puts "✅ Test executable successfully built: #{test_exe}"
  puts "   To run, execute: ./#{test_exe}"
end

# Rakefile에 추가할 태스크

desc "Build and run the Clair.Process test (single file, with library)"
task :test_process => [STATIC_LIB] do
  puts "===> Building Clair.Process test..."
  test_file = File.join(TESTS_DIR, "test_clair_process.adb")
  test_prog = File.join(BUILD_DIR, "test-clair-process")

  sh "#{GNATMAKE} -I#{SRC_DIR} #{test_file} " \
     "-o #{test_prog} " \
     "-largs #{STATIC_LIB} " \
     "-margs -D #{BUILD_DIR}"

  puts "✅ Test executable successfully built: #{test_prog}"
  puts "--> Running test:"
  sh test_prog
end

task :clean do
  puts "Cleaning up build files and config..."
  rm_rf BUILD_DIR
  rm_f FileList[ CONFIG, "mkmf.log",
                 "#{SRC_DIR}/*_h.ads",
                 "tests/test-clair-signal" ]
  rm_f BUILT_ADS
  rm_f BUILT_PROGS
end
