#include <stdio.h>
#include <inttypes.h>
#include <dlfcn.h>

const char* header = R"(-- clair-dl.ads
-- Copyright (c) 2025 Hodong Kim <hodong@nimfsoft.art>
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
-- WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
-- ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-- WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
-- ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
-- OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
--
-- THIS FILE IS AUTOMATICALLY GENERATED.
-- DO NOT EDIT THIS FILE MANUALLY.

with System;

package Clair.DL is

  type Handle is new System.Address;
  NULL_HANDLE : constant Handle := Handle (System.NULL_ADDRESS);

  -- Exceptions
  Library_Load_Error  : exception;
  Library_Close_Error : exception;
  Symbol_Lookup_Error : exception;

  -- Constants)";

const char* footer = R"(
  function  open (path : String; mode : Integer) return Handle;
  procedure close (lib : in out Handle);
  function  find_symbol (lib      : in Handle;
                         sym_name : in String) return System.Address;
  function get_dl_error return String;

end Clair.DL;)";

const char* constants =
  "  RTLD_LAZY   : constant := %" PRIuPTR ";\n"
  "  RTLD_NOW    : constant := %" PRIuPTR ";\n"
  "  RTLD_LOCAL  : constant := %" PRIuPTR ";\n"
  "  RTLD_GLOBAL : constant := %" PRIuPTR ";\n";

int main ()
{
  puts (header);
  printf (constants, RTLD_LAZY, RTLD_NOW, RTLD_LOCAL, RTLD_GLOBAL);
  puts (footer);
  return 0;
}
