#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <sys/types.h>
#include <unistd.h>

#define GET_ADA_TYPE_NAME(X) _Generic((X), \
  char:               "Interfaces.C.char", \
  signed char:        "Interfaces.C.signed_char", \
  unsigned char:      "Interfaces.C.unsigned_char", \
  short:              "Interfaces.C.short", \
  unsigned short:     "Interfaces.C.unsigned_short", \
  int:                "Interfaces.C.int", \
  unsigned int:       "Interfaces.C.unsigned", \
  long:               "Interfaces.C.long", \
  unsigned long:      "Interfaces.C.unsigned_long", \
  long long:          "Interfaces.C.long_long", \
  unsigned long long: "Interfaces.C.unsigned_long_long", \
  default:            "other" \
)

const char* header = R"(-- clair-types.ads
-- Copyright (c) 2025 Hodong Kim <hodong@nimfsoft.art>
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
-- WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
-- ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-- WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
-- ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
-- OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

-- THIS FILE IS AUTOMATICALLY GENERATED.
-- DO NOT EDIT THIS FILE MANUALLY.

with Interfaces.C;

package Clair.Types is
)";

const char* footer = R"(
end Clair.Types;)";

int main (void)
{
  mode_t  mode;
  pid_t   pid;
  ssize_t ssize;

  puts (header);

  printf ("  subtype mode_t  is %s;\n", GET_ADA_TYPE_NAME(mode));
  printf ("  subtype pid_t   is %s;\n", GET_ADA_TYPE_NAME(pid));
  printf ("  subtype ssize_t is %s;\n", GET_ADA_TYPE_NAME(ssize));

  puts (footer);
  return 0;
}
