/*
 * gen-clair-errno-raise_from_errno-adb.c
 * Copyright (C) 2025 Hodong Kim <hodong@nimfsoft.art>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#include "clair-errno-map.h"
#include <stdio.h>
#include <stdbool.h>
#include <string.h>

#ifdef __FreeBSD__
bool is_freebsd = true;
#else
bool is_freebsd = false;
#endif

const char* header = R"(-- clair-errno-raise_from_errno.adb
-- Copyright (c) 2025 Hodong Kim <hodong@nimfsoft.art>
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
-- WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
-- ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-- WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
-- ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
-- OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
--
-- THIS FILE IS AUTOMATICALLY GENERATED.
-- DO NOT EDIT THIS FILE MANUALLY.

separate (Clair.Errno)

procedure raise_from_errno (errno        : Interfaces.C.int;
                            context_info : String) is
begin
  case errno is)";

const char* footer = R"(    when others =>
      raise Unmapped_Error with
        "operation failed (errno=" & Interfaces.C.int'image(errno) &
        ") in " & context_info;
  end case;
end raise_from_errno;)";

int main ()
{
  puts (header);

  for (int i = 0; i < sizeof (errno_map) / sizeof (errno_map[0]); i++)
  {
    if (is_freebsd)
    {
      if (!strcmp(errno_map[i].name, "EWOULDBLOCK") || // EAGAIN
          !strcmp(errno_map[i].name, "ENOTSUP"))       // EOPNOTSUPP
        continue;
    }

    printf ("    when %-15s => -- %d\n", errno_map[i].name,
                                         errno_map[i].value);
    printf ("      raise Clair.Exceptions.%s \n", errno_map[i].exp);
    puts   ("            with context_info;");
  }

  puts (footer);
}
