/*
 * gen-clair-errno-ads.c
 * Copyright (C) 2025 Hodong Kim <hodong@nimfsoft.art>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <stdio.h>
#include "clair-errno-map.h"

const char* header = R"(-- clair-errno.ads
-- Copyright (c) 2025 Hodong Kim <hodong@nimfsoft.art>
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
-- WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
-- ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-- WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
-- ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
-- OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
--
-- THIS FILE IS AUTOMATICALLY GENERATED.
-- DO NOT EDIT THIS FILE MANUALLY.

with Interfaces.C;
with Clair.Platform;

package Clair.Errno is
  pragma preelaborate;
)";

const char* footer = R"(
  -- For errno values not explicitly mapped to a specific exception.
  Unmapped_Error : exception;

  function get_errno return Interfaces.C.int;
  pragma import (c, get_errno, "clair_errno_get_errno");

  procedure set_errno (value : Interfaces.C.int);
  pragma import (c, set_errno, "clair_errno_set_errno");

  function get_error_message (errno_code : Interfaces.C.int) return String;
  function format_posix_error_message (errno_code    : in Interfaces.C.int;
                                       function_name : in String;
                                       context_info  : in String) return String;
  procedure raise_from_errno (errno        : Interfaces.C.int;
                              context_info : String);
end Clair.Errno;)";

int main ()
{
  puts (header);

  for (int i = 0; i < sizeof (errno_map) / sizeof (errno_map[0]); i++)
  {
    printf ("  -- %s\n", errno_map[i].exp);
    printf ("  %-15s : constant := Clair.Platform.%s;\n",
             errno_map[i].name, errno_map[i].name);
  }

  puts (footer);
}
