-- clair-dl.ads
-- Copyright (c) 2025,2026 Hodong Kim <hodong@nimfsoft.com>
--
-- Permission to use, copy, modify, and/or distribute this software for any
-- purpose with or without fee is hereby granted.
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
-- WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
-- MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
-- ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
-- WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
-- ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
-- OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
--
-- THIS FILE IS AUTOMATICALLY GENERATED.
-- DO NOT EDIT THIS FILE MANUALLY.

with System;
with Clair.Platform;

package Clair.DL is

  type Handle is new System.Address;
  NULL_HANDLE : constant Handle := Handle(System.NULL_ADDRESS);

  -- Constants
  RTLD_LAZY   : constant := Clair.Platform.RTLD_LAZY;
  RTLD_NOW    : constant := Clair.Platform.RTLD_NOW;
  RTLD_LOCAL  : constant := Clair.Platform.RTLD_LOCAL;
  RTLD_GLOBAL : constant := Clair.Platform.RTLD_GLOBAL;

  function  open (path : String; mode : Integer) return Handle;
  procedure close (lib : in out Handle);
  function  find_symbol (lib      : in Handle;
                         sym_name : in String) return System.Address;
  function  get_dl_error return String;

end Clair.DL;
